# https://taskfile.dev

version: "3"

tasks:
    build:
        dir: "{{.USER_WORKING_DIR}}"
        cmds:
            - go mod tidy
            - go build -o ./bin/server ./cmd/server/main.go
    run:
        cmds:
            - go run cmd/server/main.go  serve --dir pb_data
    collections:
        cmds:
            - go run cmd/server/main.go migrate collections
