# For more details, read this: https://coolify.io/docs/github-actions
name: Build Static Image
on:
    pull_request:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: "production"
                type: choice
                options:
                    - production
                    - staging
            force_deploy:
                description: "Force deployment even if no changes"
                required: false
                default: false
                type: boolean

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: "egortarasov/messenger"

jobs:
    amd64:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Login to ghcr.io
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOKEN  }}
            - name: Build image and push to registry
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event_name == 'workflow_dispatch' && format('manual-{0}', github.run_number) || 'latest' }}
            - name: Deploy to Coolify
              run: |
                  curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
